# Generated by Django 5.2.1 on 2026-03-21 05:54

import diagnosis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('standby', 'Standby')], default='standby', max_length=16)),
                ('source', models.CharField(default='官方内置', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default=diagnosis.models.generate_task_id, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('requested_by', models.CharField(blank=True, max_length=64)),
                ('requested_payload', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_tasks', to='health.healthalert')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_tasks', to='assets.device')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='diagnosis.diagnosismodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_component', models.CharField(max_length=128)),
                ('severity', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('suggestion', models.TextField()),
                ('raw_output', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='diagnosis.diagnosistask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosistask',
            index=models.Index(fields=['task_id'], name='diagnosis_d_task_id_1575f5_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosistask',
            index=models.Index(fields=['status'], name='diagnosis_d_status_c5d604_idx'),
        ),
    ]
