# Generated by Django 5.2.1 on 2026-03-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_size', models.PositiveIntegerField(default=1024)),
                ('algorithm', models.CharField(choices=[('ma', '滑动平均法'), ('sg', 'Savitzky-Golay'), ('svd', '奇异值分解'), ('wavelet', '小波去噪'), ('emd', '经验模态分解'), ('eemd', '集成经验模态分解')], default='wavelet', max_length=16)),
                ('remove_anomaly', models.BooleanField(default=True)),
                ('calc_features', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_config', to='assets.device')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('rms', 'RMS'), ('p2p', '峰峰值'), ('energy', '绝对能量')], max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('raw_value', models.FloatField()),
                ('denoised_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_points', to='assets.device')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['device', 'feature', 'timestamp'], name='processing__device__fc2de2_idx')],
            },
        ),
    ]
