# Generated by Django 5.2.1 on 2026-03-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField()),
                ('rule', models.CharField(max_length=128)),
                ('level', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='info', max_length=16)),
                ('description', models.TextField()),
                ('is_ack', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='assets.device')),
            ],
            options={
                'ordering': ['-alert_time'],
                'indexes': [models.Index(fields=['device', 'alert_time'], name='health_heal_device__762185_idx'), models.Index(fields=['level'], name='health_heal_level_7d8e1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('value', models.FloatField()),
                ('source_feature', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='assets.device')),
            ],
            options={
                'ordering': ['measured_at'],
                'indexes': [models.Index(fields=['device', 'measured_at'], name='health_heal_device__d621e9_idx')],
            },
        ),
    ]
