# Generated by Django 5.2.1 on 2026-03-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('mqtt', 'MQTT'), ('db', '数据库')], default='mqtt', max_length=16)),
                ('topic_route', models.CharField(blank=True, max_length=255)),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='assets.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('waveform', models.JSONField(default=list)),
                ('fft', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='acquisition.datasource')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['source_id'], name='acquisition_source__5a749a_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['device', 'source_type'], name='acquisition_device__af3f47_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsnapshot',
            index=models.Index(fields=['source', 'captured_at'], name='acquisition_source__d064ad_idx'),
        ),
    ]
