# Generated by Django 5.2.1 on 2026-03-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('device_sn', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('model_type', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('standby', '待机')], default='online', max_length=16)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status'], name='assets_devi_status_03b2ce_idx'), models.Index(fields=['device_sn'], name='assets_devi_device__45d9b1_idx')],
            },
        ),
    ]
